apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-influxdb-project-b
  labels:
    grafana_datasource: "1"
data:
  grafana-datasource-influxdb-project-b.yaml: |
    apiVersion: 1
    datasources:
      - name: InfluxDB_v2_Flux_ProjectB
        type: influxdb
        access: proxy
        url: http://10.0.0.16:8086
        jsonData:
          version: Flux
          organization: FuncTestOrg
          defaultBucket: ProjectB
          tlsSkipVerify: true
        secureJsonData:
          token: FuncTestToken
