apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-influxdb-project-a
  labels:
    grafana_datasource: "1"
data:
  grafana-datasource-influxdb-project-a.yaml: |
    apiVersion: 1
    datasources:
      - name: InfluxDB_v2_Flux_ProjectA
        type: influxdb
        access: proxy
        url: http://10.0.0.16:8086
        jsonData:
          version: Flux
          organization: FuncTestOrg
          defaultBucket: ProjectA
          tlsSkipVerify: true
        secureJsonData:
          token: FuncTestToken
