apiVersion: apps/v1
kind: Deployment
metadata:
  name: nasnfs
  labels:
    app: nasnfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nasnfs
  template:
    metadata:
      labels:
        app: nasnfs
    spec:
      containers:
        - name: nasnfs
          image: busybox
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
          command: ["sh", "-c", 'echo "Hello, Kubernetes!" && sleep infinity']
          volumeMounts:
            - name: nas-nfs
              mountPath: /data
      volumes:
        - name: nas-nfs
          persistentVolumeClaim:
            claimName: nas-nfs-pvc
