apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-helm-chart-extraConfigmap-config
  namespace: argocd
spec:
  project: default
  source:
    path: helm/grafana-helmRepo-extraConfigmap/grafana-config
    repoURL: https://github.com/helloyuanyuan/argocd-apps.git
    targetRevision: main
  destination:
    namespace: argocd-apps
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true