apiVersion: 1
datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://10.0.0.16:8086
    jsonData:
      version: Flux
      organization: FuncTestOrg
      defaultBucket: FuncTestBucket
      tlsSkipVerify: true
    secureJsonData:
      token: FuncTestToken
