apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jmetertest
  namespace: argocd
spec:
  project: default
  source:
    path: helm/jmetertest
    repoURL: https://github.com/helloyuanyuan/argocd-apps.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: argocd-apps
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true