apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    path: charts/grafana
    repoURL: https://github.com/grafana/helm-charts.git
    targetRevision: grafana-6.46.0
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/helloyuanyuan/argocd-apps/main/helm/grafana/values.yaml
  destination:
    namespace: argocd-apps
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true