apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: argocd-apps
data:
  GF_SECURITY_ADMIN_USER: YWRtaW4=
  GF_SECURITY_ADMIN_PASSWORD: QGRtaW4xMjM=
  LDAP_BIND_PW: "xUB=RDZmT69vk4;tr*3z{{n/"