apiVersion: 1
datasources:
  - name: InfluxDB_v2_Flux_ProjectA
    type: influxdb
    access: proxy
    url: http://10.0.0.16:8086
    jsonData:
      version: Flux
      organization: FuncTestOrg
      defaultBucket: ProjectA
      tlsSkipVerify: true
    secureJsonData:
      token: FuncTestToken
  - name: InfluxDB_v2_Flux_ProjectB
    type: influxdb
    access: proxy
    url: http://10.0.0.16:8086
    jsonData:
      version: Flux
      organization: FuncTestOrg
      defaultBucket: ProjectB
      tlsSkipVerify: true
    secureJsonData:
      token: FuncTestToken
  - name: InfluxDB_v2_Flux_ProjectC
    type: influxdb
    access: proxy
    url: http://10.0.0.16:8086
    jsonData:
      version: Flux
      organization: FuncTestOrg
      defaultBucket: ProjectC
      tlsSkipVerify: true
    secureJsonData:
      token: FuncTestToken
