apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-nfs-pvc
spec:
  selector:
    matchLabels:
      type: nas-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi