[[servers]]
host = "127.0.0.1"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = true
bind_dn = "cn=admin,dc=mycompany,dc=org"
bind_password = '$__env{LDAP_BIND_PW}'
search_filter = "(cn=%s)"
search_base_dns = ["ou=Users,dc=mycompany,dc=org"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "email"