adminUser: admin
adminPassword: "@dmin123"

envRenderSecret:
  LDAP_BIND_PW: "xUB=RDZmT69vk4;tr*3z{{n/"

grafana.ini:
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  server:
    domain: "{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ .Values.ingress.hosts | first }}{{ else }}''{{ end }}"
  auth.ldap:
    enabled: true
    allow_sign_up: true
    skip_org_role_syne: true
    config_file: /etc/grafana/ldap.toml

ingress:
  enabled: true
  ingressClassName: nginx
  path: /
  pathType: Prefix
  hosts:
    - argocd.app.grafana.localdev.me

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

downloadDashboards:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi

extraConfigmapMounts:
  - name: ldap
    mountPath: /etc/grafana/ldap.toml
    configMap: grafana-config
    readOnly: false
    subPath: ldap.toml

sidecar:
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi
  datasources:
    enabled: true
    label: grafana_datasource
  dashboards:
    enabled: true
    label: grafana_dashboard
    provider:
      name: sidecarProvider
      orgid: 1
      folder: ""
      type: file
      disableDelete: false
      allowUiUpdates: true
      foldersFromFilesStructure: false
